.TH KUMOTOP "1" "July 2009" "kumotop"
.SH NAME
kumotop
.SH SYNOPSIS
kumotop server-address[:port=19800] ...
.PP
kumotop -m manager-address[:port=19700]
.SH DESCRIPTION
Show status of kumo-server and renew it continuously like
.B top
command.
.SH EXAMPLE
$ kumotop svr1 svr2 svr3 svr4
.PP
$ kumotop -m mgr1
.SH SEE ALSO
kumo-server(1).
