.TH kumostat
.SH NAME
kumostat
.SH SYNOPSIS
kumostat address[:port=19800] command [options]
.SS COMMANDS
.TP
.B pid                        
get pid of server process
.TP
.B uptime                     
get uptime
.TP
.B time                       
get UNIX time
.TP
.B version                    
get version
.TP
.B cmd_get                    
get number of get requests
.TP
.B cmd_set                    
get number of set requests
.TP
.B cmd_delete                 
get number of delete requests
.TP
.B items                      
get number of stored items
.SH DESCRIPTION
