.TH KUMOSTAT "1" "July 2009" "kumostat"
.SH NAME
kumostat
.SH SYNOPSIS
kumostat server-address[:port=19800] command

.PP
kumostat -m manager-address[:port=19700] command
.SH DESCRIPTION
Get status from Server node.
.SH COMMANDS
.TP
.B pid                        
get pid of server process
.TP
.B uptime                     
get uptime
.TP
.B time                       
get UNIX time
.TP
.B version                    
get version
.TP
.B cmd_get                    
get total number of processed get requests
.TP
.B cmd_set                    
get total number of processed set requests
.TP
.B cmd_delete                 
get total number of processed delete requests
.TP
.B items                      
get number of stored items
.TP
.B rhs                        
get rhs (routing table for Get)
.TP
.B whs                        
get whs (routing table for Set/Delete)
.TP
.B hscheck                    
check if rhs == whs
.TP
.B set_delay                  
maximize throughput at the expense of latency
.TP
.B unset_delay                
maximize throughput at the expense of latency
